/// Flutter icons Chatvpn
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GenotekIcons
///      fonts:
///       - asset: fonts/GenotekIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class GenotekIcons {
  GenotekIcons._();

  static const _kFontFam = 'GenotekIcons';

  static const String? _kFontPkg = null;
  static const IconData exitIcon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegramIcon =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyIcon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
